### ISSUE TITLE
There are too many levels

### ISSUE THREAD

**Issue by theishiopian** [theishiopian/Crystal-Us#14]
we have a huge amount of scenes, and I have no way to tell what is what or what goes where. To make things easier I have renamed all the scenes. This will, of course, break all teleporters, and i will fix them, but I need a complete map of what connects to where, as well as a list of scenes to remove. The current scenes are as follows:

- boss_testing is for testing the boss
- broken_dungeon (See #13 )
- dungeon_necklace is the dungeon with the necklace
- dungeon_sword_upgrade contains the level 2 sword upgrade
- plains_dried_river has a black-bottom river
- plains_lake has a single large body of water in the center
- plains_piss_pools is one of the oldest scenes, it is dead grass with several pools of yellow liquid
- plains_water has two large pools of blue liquid
- player_testing is my personal test scene
- town is what it sounds like

I need a map of all these scenes in relation to each other and a list of scenes to remove.

**Comment by eugievaldes** [comment]
Hey Andrew lets sit down and look at this together after Psychology class if your down.
